---
title: "Prospective students"
---

## PhD Research

We regularly welcome new PhD students to our lab. While Chris has no projects currently advertised you are welcome to [contact him](mailto:c.j.brown@utas.edu.au) if you would like to discuss opportunities

Prospective students with a background in quantitative skills are encouraged, but not essential. Training quantitative skills is something we specialise in.

Read more about Chris’ lab, research and his team on this site. [Learn more about UTas research degrees](https://www.utas.edu.au/research/degrees) and [search for active projects here](https://www.utas.edu.au/research/degrees/available-projects). 

Read below for eligibility requirements. I receive many emails about PhD positions, in general I won't respond if you don't meet these minimum requirements. 

### Eligibility requirements for PhDs

In Australia PhD applicants are awarded Australian or University funded PhD scholarships on a competitive basis. There may also be opportunities for PhD studies on scholarships that are funded directly by a grant. This system means PhD application process in Australia is different to other countries. 

The main round of PhD applications that are ranked for University and government scholarships are due for submission late September each year. Please contact Chris at least 4 weeks before hand to discuss opportunities. 

There are also other application opportunities during there year, but these primarily apply for domestic students or students applying to projects funded by grants. 

In general, PhD applications go into a competitive process that is ranked across the entire university. The exception is for grant funded projects, where students are ranked only against applicants to that specific project. 

The University and government funded positions are highly competitive, and the level of competition depends on whether you are an Australian citizen or resident or international. 

Australian applicants should have at a minimum first class Honours from their degree, or equivalent research experience (e.g. 1 year or more in a research job). 

International applicants should have equivalent of first class honours (e.g. research focused masters with GPA 6+) and either of: substantial (1+ years) research relevant work experience and/or a first authored publication in an internationally recognised journal. 

There are fewer international scholarship positions at than domestic scholarships, hence the scholarships are more competitive than for domestic applicants. 

Scholarships funded by grants may be less competitive. See my [blog](bluecology_blog.qmd) where I will advertise opportunities. 

## Honours and Masters research theses 

We regularly welcome students to do their honours or masters research thesis with us (coursework masters). Both are about 9 months duration and produce the equivalent of a research paper. 

Eligibility requirements are broadly an undergraduate degree in a relevant field. 

Learn more about [Honours degrees](https://www.utas.edu.au/courses/cse/courses/k4s-bachelor-of-marine-and-antarctic-science-with-honours) and our [Master of Marine and Antarctic Science](https://www.utas.edu.au/study/postgraduate/marine-and-antarctic-science). 

[An up-to-date listing of projects is available here](https://www.utas.edu.au/imas/study/honours-and-masters-projects)

The guidelines for Masters by Research are similar to the PhD guidelines above. 
